"""core/execution_logger.py — Logs test steps and results to PostgreSQL.

Provides functions to record task lifecycle, test plans, individual steps,
and test results. Uses SQLAlchemy async session for database operations.
"""

from __future__ import annotations

from typing import Any

from sqlalchemy import select

from core.interfaces import StepResult, TestCase, TestResult
from database.connection import async_session
from database.models import Task, TaskStep

# Maps external string task_id (UUID) to internal database auto-increment id.
_task_id_map: dict[str, int] = {}


async def log_task_created(task_id: str, task_name: str, target_url: str, config: dict) -> None:
    """Record task creation to database.

    Creates a new Task record with status "pending" and stores the mapping
    between the external string task_id and the internal auto-increment id.

    Args:
        task_id: External string identifier (UUID) for the task.
        task_name: Human-readable name of the task.
        target_url: The URL under test.
        config: Dictionary with test rules, credentials, focus areas.
    """
    merged_config = dict(config) if config else {}
    merged_config["task_id"] = task_id

    async with async_session() as session:
        task = Task(
            task_name=task_name,
            target_url=target_url,
            status="pending",
            config=merged_config,
        )
        session.add(task)
        await session.commit()
        await session.refresh(task)
        _task_id_map[task_id] = task.id


async def log_test_plan(task_id: str, test_plan: list[TestCase]) -> None:
    """Record generated test plan to database (update task.test_plan).

    Serializes the test plan to JSONB and updates the task's total_tests count.

    Args:
        task_id: External string identifier (UUID) for the task.
        test_plan: List of TestCase objects generated by the planning subgraph.
    """
    db_id = _task_id_map.get(task_id)
    if db_id is None:
        raise ValueError(f"Task with id '{task_id}' not found. Call log_task_created first.")

    plan_dicts = [case.model_dump() for case in test_plan]

    async with async_session() as session:
        task = await session.get(Task, db_id)
        if task is None:
            raise ValueError(f"Task with db_id {db_id} not found.")
        task.test_plan = plan_dicts
        task.total_tests = len(test_plan)
        await session.commit()


async def log_step(task_id: str, test_case_id: str, step: StepResult) -> None:
    """Record a single step to database (task_step table).

    Serializes step data to JSONB fields where appropriate.

    Args:
        task_id: External string identifier (UUID) for the task.
        test_case_id: Identifier like TC-001, TC-002.
        step: StepResult object containing step execution data.
    """
    db_id = _task_id_map.get(task_id)
    if db_id is None:
        raise ValueError(f"Task with id '{task_id}' not found. Call log_task_created first.")

    async with async_session() as session:
        # Save screenshot to disk if it's a base64 string
        final_screenshot_path = step.screenshot_path
        if step.screenshot_path and len(step.screenshot_path) > 1000:  # heuristic for base64
            try:
                import base64
                import uuid
                from pathlib import Path
                
                screenshots_dir = Path(__file__).resolve().parent.parent / "data" / "screenshots"
                screenshots_dir.mkdir(parents=True, exist_ok=True)
                
                filename = f"task_{db_id}_tc_{test_case_id}_step_{step.step_index}_{uuid.uuid4().hex[:8]}.png"
                filepath = screenshots_dir / filename
                
                # Strip data URL prefix if present (though take_screenshot returns raw base64)
                b64_data = step.screenshot_path
                if b64_data.startswith('data:image'):
                    b64_data = b64_data.split(',')[1]
                    
                filepath.write_bytes(base64.b64decode(b64_data))
                final_screenshot_path = filename  # Only store filename in DB
            except Exception as e:
                print(f"Failed to save screenshot to disk: {e}")
                final_screenshot_path = "" # Avoid saving massive string to DB on failure

        task_step = TaskStep(
            task_id=db_id,
            test_case_id=test_case_id,
            step_index=step.step_index,
            action_type=step.action_type,
            action_target=step.action_target,
            action_args=step.action_args if step.action_args else None,
            result=step.result,
            screenshot_path=final_screenshot_path,
            change_report=step.change_report.model_dump() if step.change_report else None,
            assertion_result=step.assertion.model_dump() if step.assertion else None,
        )
        session.add(task_step)
        await session.commit()


async def log_test_result(task_id: str, result: TestResult) -> None:
    """Record test case result, update task's passed_tests/failed_tests counts.

    Args:
        task_id: External string identifier (UUID) for the task.
        result: TestResult object containing the test case execution outcome.
    """
    db_id = _task_id_map.get(task_id)
    if db_id is None:
        raise ValueError(f"Task with id '{task_id}' not found. Call log_task_created first.")

    async with async_session() as session:
        task = await session.get(Task, db_id)
        if task is None:
            raise ValueError(f"Task with db_id {db_id} not found.")

        if result.status == "passed":
            task.passed_tests += 1
        elif result.status == "failed":
            task.failed_tests += 1
        # "skipped" and "incomplete" do not increment either counter

        await session.commit()


async def get_task_steps(task_id: str, test_case_id: str = "") -> list[dict[str, Any]]:
    """Query task steps. If test_case_id not provided, return all steps.

    Args:
        task_id: External string identifier (UUID) for the task.
        test_case_id: Optional filter for a specific test case.

    Returns:
        List of step dictionaries ordered by step_index.
    """
    db_id = _task_id_map.get(task_id)
    if db_id is None:
        raise ValueError(f"Task with id '{task_id}' not found. Call log_task_created first.")

    async with async_session() as session:
        stmt = select(TaskStep).where(TaskStep.task_id == db_id)
        if test_case_id:
            stmt = stmt.where(TaskStep.test_case_id == test_case_id)
        stmt = stmt.order_by(TaskStep.step_index)
        result = await session.execute(stmt)
        steps = result.scalars().all()

        return [
            {
                "id": step.id,
                "task_id": step.task_id,
                "test_case_id": step.test_case_id,
                "step_index": step.step_index,
                "action_type": step.action_type,
                "action_target": step.action_target,
                "action_args": step.action_args,
                "result": step.result,
                "screenshot_path": step.screenshot_path,
                "change_report": step.change_report,
                "assertion_result": step.assertion_result,
                "created_at": step.created_at.isoformat() if step.created_at else None,
            }
            for step in steps
        ]
