"""
database/models.py — SQLAlchemy ORM models for task, task_step, and report tables.

Defines the database schema using SQLAlchemy declarative base.
Tables: task, task_step, report.
"""

from __future__ import annotations

from sqlalchemy import BigInteger, DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Base class for all ORM models."""
    pass


class Task(Base):
    """Represents a testing task.

    Attributes:
        id: Auto-increment primary key.
        task_name: Human-readable task name.
        target_url: The URL under test.
        status: Current status (pending, running, completed, failed, cancelled).
        config: JSONB with test rules, credentials, focus areas.
        test_plan: JSONB list of TestCase dicts generated by planning subgraph.
        total_tests: Total number of test cases.
        passed_tests: Number of passed test cases.
        failed_tests: Number of failed test cases.
        started_at: Timestamp when the task started (nullable).
        completed_at: Timestamp when the task completed (nullable).
        created_at: Timestamp when the task was created.
        steps: Related TaskStep records.
        reports: Related Report records.
    """

    __tablename__ = "task"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    task_name: Mapped[str] = mapped_column(String(255), nullable=False)
    target_url: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="pending")
    config: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    test_plan: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    total_tests: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    passed_tests: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    failed_tests: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    started_at: Mapped[DateTime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[DateTime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[DateTime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())

    steps: Mapped[list["TaskStep"]] = relationship("TaskStep", back_populates="task", cascade="all, delete-orphan")
    reports: Mapped[list["Report"]] = relationship("Report", back_populates="task", cascade="all, delete-orphan")


class TaskStep(Base):
    """Represents a single step executed during a task.

    Attributes:
        id: Auto-increment primary key.
        task_id: Foreign key to task.id.
        test_case_id: Identifier like TC-001, TC-002.
        step_index: Step sequence number.
        action_type: Type of action (click, input_text, navigate, etc.).
        action_target: Target element or description.
        action_args: JSONB with action parameters.
        result: Result description.
        screenshot_path: Path to the screenshot file.
        change_report: JSONB with ChangeReport from change detector.
        assertion_result: JSONB with assertion status and reasoning.
        created_at: Timestamp when the step was recorded.
        task: Related Task record.
    """

    __tablename__ = "task_step"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    task_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("task.id", ondelete="CASCADE"), nullable=False)
    test_case_id: Mapped[str] = mapped_column(String(50), nullable=False)
    step_index: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    action_type: Mapped[str] = mapped_column(String(50), nullable=False)
    action_target: Mapped[str] = mapped_column(Text, nullable=False)
    action_args: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    result: Mapped[str] = mapped_column(Text, nullable=False, default="")
    screenshot_path: Mapped[str] = mapped_column(Text, nullable=False, default="")
    change_report: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    assertion_result: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    created_at: Mapped[DateTime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())

    task: Mapped["Task"] = relationship("Task", back_populates="steps")


class Report(Base):
    """Represents a test report generated for a task.

    Attributes:
        id: Auto-increment primary key.
        task_id: Foreign key to task.id.
        report_path: Path to the generated report file.
        summary: AI-generated summary text.
        created_at: Timestamp when the report was created.
        task: Related Task record.
    """

    __tablename__ = "report"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    task_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("task.id", ondelete="CASCADE"), nullable=False)
    report_path: Mapped[str] = mapped_column(Text, nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False, default="")
    created_at: Mapped[DateTime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())

    task: Mapped["Task"] = relationship("Task", back_populates="reports")


class AgentMemory(Base):
    """Represents a piece of memory/knowledge learned by the agent.

    Attributes:
        id: Auto-increment primary key.
        scope_type: Memory scope type ('global' or 'domain').
        scope_value: Scope target (e.g., '*' for global, '192.168.31.155' for domain).
        memory_key: A short description/index for the memory.
        memory_value: The detailed knowledge or rule text.
        created_at: Timestamp when created.
        updated_at: Timestamp when last updated.
    """

    __tablename__ = "agent_memory"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    scope_type: Mapped[str] = mapped_column(String(50), nullable=False)
    scope_value: Mapped[str] = mapped_column(Text, nullable=False)
    memory_key: Mapped[str] = mapped_column(Text, nullable=False)
    memory_value: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[DateTime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())
    updated_at: Mapped[DateTime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now())
